### ISSUE TITLE
Hitting re-record deletes my script

### ISSUE THREAD

**Issue by jmadans** [codeforamerica/cityvoice-survey-builder#50]
I have to rewrite my script everytime I re-record. 
![screen shot 2015-01-15 at 12 29 28 am](https://cloud.githubusercontent.com/assets/1261618/5754433/970e8df2-9c4d-11e4-943d-fbcb6812c4ec.png)

**Comment by jmadans** [comment]
This is - still -  super annoying

**Comment by daguar** [comment]
Laying out implementation (cc @migurski ) if this sucks, there are two approaches:

1. For re-recording, have Javascript just clear the audio stuff back to a default state, rather than reloading the page

or

2. Have the "re-record" button actually submit data back to the form, and then have that same route essentially reload but populate the text field with the param submitted rather than whatever is in the var before

**Comment by migurski** [comment]
FWIW here’s the hacky way I did it so far: https://github.com/codeforamerica/cityvoice-survey-builder/commit/100eae801ba14e9042c4a056b1423c4274aeb43e and https://github.com/codeforamerica/cityvoice-survey-builder/commit/073753f0756acf8535d824ef92c7990739c37cf5

**Comment by migurski** [comment]
…but I like your second suggestion most of all. Just didn’t feel qualified enough to write and test any poetry mode.

**Comment by jmadans** [comment]
Done!
