### ISSUE TITLE
Locations should read as place/names instead of addresses

### ISSUE THREAD

**Issue by jmadans** [codeforamerica/cityvoice-survey-builder#78]
When users add their survey locations as addresses they are disappointed/confused to find that the City Voice site doesn't refer to them as place names. For instance, CityVoice site lists a Survey location as 508 Pkwy instead of Etowah River Park. 

In user testing with Camille, CIO of Canton, she forgot which of her survey locations was at 508 Rivenstone Pkwy address and felt that would be confusing for her residents. Camille is _not comfortable launching her CityVoice survey_ until this is fixed. 

### Two ways to improve this: ###
1. Small fix: Put placeholder text in the Add Location Box that suggests their they structure their location as *Location Name, Street Number, City, State,*
2. Bigger fix: Add a separate *Place/Name* field so the builder asks for the address and Place/Name for each location

@daguar @migurski What do you think? Also curious to hear if there is a way for me to edit this on the back end without making her create a new survey. 

<img width="712" alt="screen shot 2015-07-09 at 12 24 29 pm" src="https://cloud.githubusercontent.com/assets/1261618/8753950/af3a4594-2c74-11e5-94f5-147058d98907.png">

**Comment by daguar** [comment]
I actually implemented most of this feature before, but commented it out because I got feedback that we wanted to simplify it — but THE USER NEEDS PREVAIL.

I've pushed up the work that implements a simple step after location selection that lets you edit names to the branch here: https://github.com/codeforamerica/cityvoice-survey-builder/tree/add-step-for-editing-location-names

The experience looks like this:

(1) Add locations, same as before

![screen shot 2015-07-17 at 12 54 34 pm](https://cloud.githubusercontent.com/assets/994938/8755917/45d4fe46-2c83-11e5-9d97-37a504f96270.png)

(2) A step to edit the names (by default, the box starts filled in with the address)

before editing...

![screen shot 2015-07-17 at 12 54 44 pm](https://cloud.githubusercontent.com/assets/994938/8755931/6134bd84-2c83-11e5-83bd-dc97a6a5cdbd.png)

after editing...

![screen shot 2015-07-17 at 12 54 56 pm](https://cloud.githubusercontent.com/assets/994938/8755921/54461618-2c83-11e5-81f6-9640e8395d64.png)

@migurski — want to pull this down and give it a try to see if it works on your end? 
@jmadans — want to suggest copy for the name-change view? (it's `views/locations_edit.rb`)

**Comment by daguar** [comment]
Also a few responses to your specific questions @jmadans:

> Bigger fix: Add a separate Place/Name field so the builder asks for the address and Place/Name for each location

This is more or less what I did, but I implemented it as a separate step with the idea that the lowest-friction approach would be defaulting to address, and the idea that in a second step they could name the addresses however they want. Think this works for the need?

> Small fix: Put placeholder text in the Add Location Box that suggests their they structure their location as Location Name, Street Number, City, State,

I wouldn't suggest this. The way that part works is it uses Google's geocoder to search for the text put in the box, and then grabs the resulting address, using that as the temporary name. You COULD do something where you parse out the name part of the input from the user first and only use the later stuff, but I think "putting the thing on a map" and "naming the thing" are different concerns that shouldn't be mixed.

> Also curious to hear if there is a way for me to edit this on the back end without making her create a new survey. 

How many locations are there? If there aren't many, the easiest way is probably just to open a rails console on the server and edit the database entities to change their name. (Not ideal, because the CSV will be the same, but the CSV is only really used for that initial location load.)
